### ISSUE TITLE
How to skip trace for particular endpoint with java-agent

### ISSUE THREAD

**Issue by sayboras** [DataDog/dd-trace-java#1046]
I am using java-agent as mentioned https://docs.datadoghq.com/tracing/setup/java/ for tracing and metrics.

My service is having one internal health check endpoint, and I would like to skip tracing for this. Please let me know how I can achieve this. 

Normally, for opentracing + springboot, I can set the below configuration to do so.
```
opentracing:
  spring:
    web:
      skip-pattern: /health
```
