### ISSUE TITLE
Is it possible to disable capturing stacktrace?

### ISSUE THREAD

**Issue by iinm** [DataDog/dd-trace-java#1180]
I would like to disable capturing stacktrace because those may contain user's personal information.  In our case, user's name is accidentally captured with `org.springframework.web.bind.MethodArgumentNotValidException`.
<img width="1006" alt="Screen Shot 2020-01-15 at 13 05 42 copy" src="https://user-images.githubusercontent.com/8685693/72490136-a635a600-3859-11ea-9a6a-440bd0e54808.png">

Are there any option to disable capturing stacktrace?

**Comment by jeremy-lq** [comment]
@iinm We should be able to accomplish this, but we'll need some additional information. Please open a support ticket and we'll pickup from there. Thanks.

**Comment by iinm** [comment]
We found that it can be masked.  Thank you.

datadog.yaml example:
```yaml
apm_config:
  enabled: true
  replace_tags:
    # https://github.com/DataDog/dd-trace-java/blob/v0.15.0/dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
    - name: "error.stack"
      pattern: ".*"
      repl: "MASKED"
    - name: "error.msg"
      pattern: ".*"
      repl: "MASKED"
```
