### ISSUE TITLE
Add JMX New metric

### ISSUE THREAD

**Issue by royremit** [DataDog/dd-trace-java#3063]
Hi I'm not sure if its the right place to post a question but Ill try it here.

We are building a docker container and using the java agent for datadog. My goal is to start sending Hikaricp pool metrics to datadog 

we start our application like this
```
CMD ["/bin/sh", "-c", \
     "java -XX:MinRAMPercentage=50.0 \
     -XX:MaxRAMPercentage=80.0 \
     -javaagent:./dd-java-agent.jar \
     -Ddd.jmxfetch.config.dir=metrics \
     -Ddd.jmxfetch.config=conf.yaml \
     -jar ./apps.jar" \
 ]
```

I created a file conf.yaml like this in metrics\cong.yaml

```
init_config:
  is_jmx: true
  collect_default_metrics: true
  conf:
    - include:
      domain: com.zaxxer.hikari
      bean_regex:
        - com.zaxxer.hikari:type=Pool.*
      name: Pool
      attribute:
        ActiveConnections:
          metric_type: gauge
          alias: hikaricp.activeconnections
        IdleConnections:
          metric_type: gauge
          alias: hikaricp.idleconnections
        ThreadsAwaitingConnection:
          metric_type: gauge
          alias: hikaricp.threadsawaitingconnection
        TotalConnections:
          metric_type: gauge
          alias: hikaricp.totalconnections

instances:
  - host: 127.0.0.1
```

I don't get any error when my application start but nothing look to work....

Do I miss something important? How I could debug this to see if anything is wrong?

Thanks

**Comment by royremit** [comment]
I did more modification without a lot of more progress
my file look like this now ;

```
init_config:
instances:
  - jvm_direct: true
    name: hubspot-deletion
    conf:
      - include:
        bean_regex:
          - com\.zaxxer\.hikari:type=Pool (.*
        attribute:
          ActiveConnections:
            metric_type: gauge
            alias: hikaricp.activeconnections
          IdleConnections:
            metric_type: gauge
            alias: hikaricp.idleconnections
          ThreadsAwaitingConnection:
            metric_type: gauge
            alias: hikaricp.threadsawaitingconnection
          TotalConnections:
            metric_type: gauge
            alias: hikaricp.totalconnections

```

still no luck.

**Comment by devinsba** [comment]
Sorry, I'm not sure how to help you here. You might get more support in https://github.com/DataDog/jmxfetch

**Comment by bbensky** [comment]
@royremit - We are trying to get the same Hikaricp Pool metrics to Datadog - were you able to find a configuration that worked?

**Comment by willianccs** [comment]
I need to send some metrics about Hikaricp too.
It's necessary to build an custom image to aim this? I saw this [documentation](https://docs.datadoghq.com/integrations/hikaricp/) page, but I confused about that.
Currenty we using datadog-agent-jmx image inside Kubernetes to fetch metrics about ignite, for Hikaricp this way doesn't works?

**Comment by er1c** [comment]
This worked for me:

```
init_config:

instances:
  - jvm_direct: true
    name: hikari-slick-monitoring
    collect_default_jvm_metrics: false
    collect_default_metrics: false
    refresh_beans: 60
    conf:
      - include:
          bean_regex: "com.zaxxer.hikari:type=Pool \\((.*)\\)"
          tags:
            pool: $1
          attribute:
            ActiveConnections:
              metric_type: gauge
              alias: hikaricp.connections.active
            IdleConnections:
              metric_type: gauge
              alias: hikaricp.connections.idle
            TotalConnections:
              metric_type: gauge
              alias: hikaricp.connections.total
            PendingThreads:
              metric_type: gauge
              alias: hikaricp.connections.pending
            MaxConnections:
              metric_type: gauge
              alias: hikaricp.connections.max
            MinConnections:
              metric_type: gauge
              alias: hikaricp.connections.min
            ConnectionAcquireMillis:
              metric_type: timer
              alias: hikaricp.connections.acquire
            ConnectionUsageMillis:
              metric_type: timer
              alias: hikaricp.connections.usage
            ConnectionTimeoutRate:
              metric_type: counter
              alias: hikaricp.connections.timeout
            ConnectionCreationMillis:
              metric_type: timer
              alias: hikaricp.connections.creation
      - include:
          bean_regex: "slick:type=AsyncExecutor,name=(.*)"
          tags:
            pool: $1
          attribute:
            MaxThreads:
              metric_type: gauge
              alias: slick.executor.threads.max
            QueueSize:
              metric_type: gauge
              alias: slick.executor.queue.size
            MaxQueueSize:
              metric_type: gauge
              alias: slick.executor.queue.max_size
            ActiveThreads:
              metric_type: gauge
              alias: slick.executor.threads.active
            TotalExecutionTime:
              metric_type: counter
              alias: slick.executor.total_execution_time

```

**Comment by mwisnicki** [comment]
@royremit 

> I did more modification without a lot of more progress my file look like this now ;
> 
> ```
> init_config:
> instances:
>   - jvm_direct: true
>     name: hubspot-deletion
>     conf:
>       - include:
>         bean_regex:
>           - com\.zaxxer\.hikari:type=Pool (.*
>         attribute:
>           ActiveConnections:
>             metric_type: gauge
>             alias: hikaricp.activeconnections
>           IdleConnections:
>             metric_type: gauge
>             alias: hikaricp.idleconnections
>           ThreadsAwaitingConnection:
>             metric_type: gauge
>             alias: hikaricp.threadsawaitingconnection
>           TotalConnections:
>             metric_type: gauge
>             alias: hikaricp.totalconnections
> ```
> 
> still no luck.

Add 2 spaces to everything below `include` line.

**Comment by er1c** [comment]
> [@royremit](https://github.com/royremit)
> 
> > I did more modification without a lot of more progress my file look like this now ;
> > ```
> > init_config:
> > instances:
> >   - jvm_direct: true
> >     name: hubspot-deletion
> >     conf:
> >       - include:
> >         bean_regex:
> >           - com\.zaxxer\.hikari:type=Pool (.*
> >         attribute:
> >           ActiveConnections:
> >             metric_type: gauge
> >             alias: hikaricp.activeconnections
> >           IdleConnections:
> >             metric_type: gauge
> >             alias: hikaricp.idleconnections
> >           ThreadsAwaitingConnection:
> >             metric_type: gauge
> >             alias: hikaricp.threadsawaitingconnection
> >           TotalConnections:
> >             metric_type: gauge
> >             alias: hikaricp.totalconnections
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > still no luck.
> 
> Add 2 spaces to everything below `include` line.

` - com\.zaxxer\.hikari:type=Pool (.*` this is an incorrect regex as well you would need to escape the `\(` you could also create this as a string and not as an array

**Comment by sdzharkov** [comment]
For the next person who gets stuck on this, here's what worked for us. We have Datadog configured via a Helm chart in K8s.

 The config I am sharing relies on [JMX autodiscovery being enabled](https://docs.datadoghq.com/containers/guide/autodiscovery-with-jmx/?tab=helm#installation).

We added this annotation:
```yaml
      annotations:
        ad.datadoghq.com/api.checks: |
          {
            "jmx": {
              "init_config": {
                "is_jmx": true,
                "collect_default_metrics": true,
                "collect_default_jvm_metrics": true
              },
              "instances": [
                {
                  "host": "%%host%%",
                  "port": 9010,
                  "name": "hikari-jmx-%%host%%",
                  "conf": [
                    {
                      "include": {
                        "domain": "com.zaxxer.hikari",
                        "bean_regex": [
                          "com.zaxxer.hikari:type=Pool.*"
                        ],
                        "attribute": {
                          "ActiveConnections": {
                            "metric_type": "gauge",
                            "alias": "hikaricp.active_connections"
                          },
                          "IdleConnections": {
                            "metric_type": "gauge", 
                            "alias": "hikaricp.idle_connections"
                          },
                          "ThreadsAwaitingConnection": {
                            "metric_type": "gauge",
                            "alias": "hikaricp.threads_awaiting_connection"
                          },
                          "TotalConnections": {
                            "metric_type": "gauge",
                            "alias": "hikaricp.total_connections"
                          }
                        }
                      }
                    }
                  ]
                }
              ]
            }
          }
```

You will also need the following options, we pass them in as env vars
```yaml
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.local.only=false
                -Dcom.sun.management.jmxremote.port=9010
                -Dcom.sun.management.jmxremote.rmi.port=9010
                -Dcom.sun.management.jmxremote.ssl=false
                -Djava.rmi.server.hostname=$(POD_IP)
```

Make sure to expose the service port 9010
```
apiVersion: v1
kind: Service
metadata:
  namespace: <your namespace>
  name:api
spec:
  ports:
    - port: 9010
      name: jmx
      targetPort: 9010
      protocol: TCP
  type: NodePort
  selector:
    app: realtime-api
```
