### ISSUE TITLE
Adding order_updates and batch_versioned_data disables update/insert MySQL spans

### ISSUE THREAD

**Issue by agdt3** [DataDog/dd-trace-java#6127]
Added batching to updates/inserts in a spring boot app and promptly lost the ability to see update/insert MySQL spans.

Spring Boot: 3.0.6
Java: 17
dd-trace (pom and jar): 1.22.0

Config:
```
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true
        jdbc:
          batch_size: 30
```

Select spans are visible:
<img width="991" alt="Screenshot 2023-11-01 at 7 15 27 AM" src="https://github.com/DataDog/dd-trace-java/assets/1611192/a3fafd30-9276-49bf-b8d3-9b667dbf6007">

Inserts/updates are not:
<img width="515" alt="Screenshot 2023-11-01 at 7 17 52 AM" src="https://github.com/DataDog/dd-trace-java/assets/1611192/731da812-6cad-422f-9a5f-54cc072e8754">
