### ISSUE TITLE
Question about traceId propagation in Spring Boot 3.x app using RestTemplate and Micrometer

### ISSUE THREAD

**Issue by mszumlanski** [DataDog/dd-trace-java#6307]
Hey, I see some inconsistencies related to traceId on my app. I have 2 services - Service1 is using Spring Boot 3.1.6 with SL4J/Logback.

I use DataDog as a Java agent and added following dependencies:
```
io.micrometer:micrometer-tracing
io.micrometer:micrometer-tracing-bridge-otel
io.micrometer:micrometer-registry-datadog
```
and following logback configuration:

```
  <appender class="ch.qos.logback.core.ConsoleAppender" name="STDOUT">
    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] [%X{spanId}] %-5level %logger{5} - %msg%n</pattern>
    </encoder>
  </appender>

  <appender class="ch.qos.logback.core.ConsoleAppender" name="STDOUT_JSON">
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
      <!-- This configuration resolves a dependency issue. See the below link for more information. -->
      <!-- https://github.com/logfellow/logstash-logback-encoder/issues/387#issuecomment-581603444 -->
      <findAndRegisterJacksonModules>false</findAndRegisterJacksonModules>
    </encoder>
  </appender>
```
I also have following configuration in .yml file:
```
  tracing:
    sampling:
      probability: 1.0
  datadog:
    metrics:
      export:
        uri: https://app.datadoghq.com
        enabled: true
        api-key: MANAGEMENT_DATADOG_METRICS_EXPORT_API_KEY
        step: 10s
        application-key: MANAGEMENT_DATADOG_METRICS_EXPORT_APPLICATION_KEY
  metrics:
    tags:
      application: ${spring.application.name}
```
I did not add any extra code related to tracing or metrics.

First off I'm calling one of Service1 endpoints with no trace context headers whatsoever. Initially on Service1 I'm seeing different values in MDC and stdout logs for `traceId` and `dd.trace_id`. Afer I make a call to Service2 using RestTemplate  I can see that `traceparent` header in request, specifically it's traceId part is made up of `_dd.p.tid` tag and dd.trace_id hex representation values (made up of two 64 bit parts). It is then deserialised and then in Service2 I'm seeing both `traceId` and `dd.trace_id` set to same value, the one that `dd.trace_id` originally held - this is expected.

- Are u guys by default injecting any sort of instrumentation/interceptors/whatever so that RestTemplate builds a `traceparent` header out of DataDog values? It was my initial assumption that framework will grab `traceId` value and not dd stuff to build request metadata.
- This question might be out of scope but do you have any clue why traceId is initially having different value on Service1?
