### ISSUE TITLE
DD_TRACE_HEADER_BAGGAGE environment variable is not being honoured

### ISSUE THREAD

**Issue by nabeelpaytrix** [DataDog/dd-trace-java#7303]
I have set this environment variable within my application pods as follows:

```
containers:
  - name: pod-b
     env:
       - name: DD_TRACE_HEADER_BAGGAGE
          value: header-a, header-b, header-c
```

My Trace is as follows, Pod A --> Pod B --> Pod C

Pod A is sending the headers `header-a` `header-b` and `header-c` to Pod B
But Pod B does not forward these headers to Pod C
