### ISSUE TITLE
Add ability to customize JMXFetch initialization

### ISSUE THREAD

**Issue by sblumenthalAtBraze** [DataDog/dd-trace-java#806]
Right now, looking through the code for the included JMXFetch in this repo, it looks like the initial configuration of the underlying JMXFetch instance is hard coded (see here: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java#L23 which points to here: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-jmxfetch/src/main/resources/jmxfetch-config.yaml).

This means that if anyone needs to run JMXFetch with custom settings (like, say, increasing the returned metric limit, or removing the default collected metrics because there is a limit and not all of them are useful for a given workflow), they either have to fork the repo in order to change the file contents, or not use this version of JMXFetch at all, which is unfortunate because of how convenient it is for application bundling and deploying over the alternative.

Is there any chance that the init config file path can be added as a jvm arg, so that the ability to override it is there?

**Comment by tylerbenson** [comment]
We provide additional jmxfetch options that are passed from the javaagent down through.  For example, `dd.jmxfetch.metrics-configs` might provide what you're looking for.

More config options are listed here: https://docs.datadoghq.com/tracing/setup/java/#configuration

If there's a specific configuration you're unable to achieve, let us know and we can try to add config options for it.

**Comment by brentm5** [comment]
I know that we use the `dd.jmxfetch.metrics-configs` setting to collect metrics from a different java container format.  The only issue we have seen is that on startup the metrics aren't guaranteed to be there by the time JMX-Fetch starts up and analysis the beans to report.  

We improved our story by setting `dd.jmxfetch.refresh-beans-period` to be 120 seconds instead of 600 seconds which allowed the values to start working in 2 minutes instead of 10.  I think ideally this could be improved by either searching for metrics more aggressively on startup and then returning back to 600 second intervals or simply waiting to start jmxfetch for a configureable amount of time.

Other than that things have been working well!

**Comment by drobert** [comment]
We, similarly, ran into the issue of having some lazily-evaluated beans we didn't want to wait 10 minutes for, so we dropped the refresh period to 120. It would be valuable to have a refresh-backoff strategy on startup with a max value specified so that beans can be discovered relatively quickly on startup but then we don't pay the price forever.

In a separate customization vein, I don't see any ability to customize the logging level for JMXFetch when run from dd-trace-java. It's fairly noisy and the rest of our datadog agents honor the `DD_LOG_LEVEL=Error` environment variable we'd set.

**Comment by sblumenthalAtBraze** [comment]
@tylerbenson the metrics config setting that you provide seems to only work for adding custom metrics to pull (the things that would be located under instances.conf in the solo jmx config if I were to use it outside of the java agent).

The reason it is an issue is because I am hitting the jmx metrics limit per host (kafka consumer app, and some metrics we REQUIRE partition level granularity...they add up fast). I looked through the JMXFetch code and found the config I needed to change, and opened a ticket with datadog support (as the documentation says to do here: https://docs.datadoghq.com/integrations/java/#the-350-metric-limit), and they confirmed for me that the config I found was correct.

However, when I try to create a yaml file similar to this one (I put collect_default_metrics in place of the metric limit override, in case you would prefer that not be made common knowledge here since it isn't documented anywhere):
```
init_config:
  is_jmx: true
  new_gc_metrics: true
instances:
- jmx_url: service:jmx:local:///
  collect_default_metrics: false
  tags:
    testing: true
  conf:
    - include:
        domain: 'kafka.consumer'
        bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*,topic=.*,partition=.*'
        attribute:
          records-lag:
            metric_type: gauge
            alias: kafka.consumer.consumer_lag
    - include:
        domain: 'kafka.consumer'
        bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*-consumer(?!,)'
        attribute:
          records-consumed-rate:
            metric_type: gauge
            alias: kafka.consumer.records_consumed_total
```

the java agent fails to parse the file with the following message:
```
 2019-04-10 19:10:35,960 | INFO | Instance | Reading metric config file /metrics.yaml
 2019-04-10 19:10:35,965 | WARN | Instance | Cannot parse yaml file /metrics.yaml
 java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.ArrayList
 	at org.datadog.jmxfetch.Instance.loadMetricConfigFiles(Instance.java:192)
 	at org.datadog.jmxfetch.Instance.<init>(Instance.java:160)
 	at org.datadog.jmxfetch.App.instantiate(App.java:623)
 	at org.datadog.jmxfetch.App.init(App.java:685)
 	at org.datadog.jmxfetch.App.run(App.java:149)
 	at datadog.trace.agent.jmxfetch.JMXFetch$1.run(JMXFetch.java:75)
 	at java.lang.Thread.run(Thread.java:748)
 2019-04-10 19:10:35,986 | INFO | Instance | Trying to connect to JMX Server at service:jmx:local:///
 2019-04-10 19:10:35,986 | INFO | Instance | Connection closed or does not exist. Creating a new connection!
 2019-04-10 19:10:36,036 | INFO | ConnectionFactory | Connecting using JMX Local
```

The format that DOES WORK, when adding a file using the metrics-configs setting, is this one:
```
- include:
    domain: 'kafka.consumer'
    bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*,topic=.*,partition=.*'
    attribute:
      records-lag:
        metric_type: gauge
        alias: kafka.consumer.consumer_lag
- include:
    domain: 'kafka.consumer'
    bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*-consumer(?!,)'
    attribute:
      records-consumed-rate:
        metric_type: gauge
        alias: kafka.consumer.records_consumed_total
```

Unfortunately, that doesn't allow me to specify the config value I need. I figured that it would be easier to change this parameter to have a user override ( https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java#L23 ) than it would be to add a setting to allow me to configure a value that is purposefully not exposed in the documentation for the datadog java integration
