### ISSUE TITLE
Error using dd-trace-java 1.44.1 with mule 4.6.9:11-java17

### ISSUE THREAD

**Issue by Miladiir** [DataDog/dd-trace-java#8130]
After the update to latest version of dd-trace-java from 1.43.0 to 1.44.1 and using a mule runtime engine of 4.6.9:11-java17 we get the following error:
```
********************************************************************************
Message               : class datadog.trace.instrumentation.mule4.DDEventTracer (in unnamed module @0x4683f197) cannot access class org.mule.runtime.tracer.customization.impl.info.ExecutionInitialSpanInfo (in module org.mule.runtime.tracer.customization.impl) because module org.mule.runtime.tracer.customization.impl does not export org.mule.runtime.tracer.customization.impl.info to unnamed module @0x4683f197
Element               : <redacted>/processors/0 @<redacted><redacted>.xml:17 (Choice)
Element DSL           : <choice doc:name="Choice" doc:id="531f2eff-7c80-485a-b45b-85b1d88f9627">
<when expression="<redacted>") == "true"]">
<logger level="INFO" doc:name="Logger" doc:id="222c089d-00e1-4d1e-b7a6-008af09ae009" message="<redacted>"></logger>
<flow-ref doc:name="Flow Reference" doc:id="de509546-2c14-4cd3-a991-7663ccec2fff" name="<redacted>"></flow-ref>
</when>
</choice>
Error type            : MULE:CRITICAL
FlowStack             : at <redacted>

  (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************
```

Datadog related settings in deployment yaml are as follows:

```
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/role: mule-api
        tags.datadoghq.com/service: <redacted>
        tags.datadoghq.com/source: anypoint
        tags.datadoghq.com/version: 81abbbe7-a34b-46e5-962d-4a4e3f9e70e9
      annotations:
        ad.datadoghq.com/app.logs: '[{"source": "anypoint"}]'
        admission.datadoghq.com/java-lib.version: v1.44.1
    spec:
      containers:
        - name: app
          image: <redacted>/mulesoft/poseidon-runtime-4.6.9:11-java17
          env:            
            - name: DD_INTEGRATION_MULE_ENABLED
              value: "true"
            - name: DD_INTEGRATION_GRIZZLY_CLIENT_ENABLED
              value: "true"
            - name: DD_INTEGRATION_GRIZZLY_FILTERCHAIN_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_GIT_COMMIT_SHA
              value: <redacted>
            - name: DD_GIT_REPOSITORY_URL
              value: <redacted>
            - name: DD_PROFILING_DDPROF_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
```

Both versions are the latest (stable) versions of today.
