### ISSUE TITLE
munit and junit test reporting does not work when sbt runs tests in fork mode

### ISSUE THREAD

**Issue by mwisnicki** [DataDog/dd-trace-java#8665]
### Tracer Version(s)

1.47.3~4a85e1fff5

### Java Version(s)

21.0.2

### JVM Vendor

Eclipse Adoptium / Temurin

### Bug Report

When sbt is configured to run tests in fork mode, neither munit nor junit tests are reported to datadog.
Forking mode works for scalatest.

### Expected Behavior

munit with `Test/fork := true` reports tests to datadog.

### Reproduction Code

`build.sbt`
```scala
scalaVersion := "3.3.5"
Test / fork := true // comment it out to make this work
libraryDependencies ++= Seq(
  "junit" % "junit" % "4.13.2" % Test,
  "com.github.sbt" % "junit-interface" % "0.13.3" % Test,
  "org.scalameta" %% "munit" % "1.1.0" % Test,
)
```

`src/test/scala/ExampleTest.scala`
```scala
class ExampleJunitTest {
  @org.junit.Test
  def hello(): Unit = {
    println("Hello from JUnit")
  }
}

class ExampleMunitTest extends munit.FunSuite {
  test("hello") {
    println("Hello from MUnit")
  }
}
```

`project/build.properties`
```
sbt.version=1.10.11
```

Simplified snippet from `.github/workflows/test.yaml`
```yaml
jobs:
  tests:
    steps:
      - uses: sbt/setup-sbt@v1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: datadog/test-visibility-github-action@v2
        with:
          languages: java
          api_key: ${{ secrets.DATADOG_API_KEY }}
          service: foo
      - run: sbt test
```

**Comment by nikita-tkachenko-datadog** [comment]
Hi @mwisnicki, thank you for reporting this!
The reason tests are not reported to Datadog is that the DD tracer is only injected into the parent SBT process, and not into the forked JVMs that execute the tests.
Could you please try using the `java-instrumented-build-system: all` GitHub Action setting? That will ensure the tracer is injected into every JVM. 
```
- uses: datadog/test-visibility-github-action@v2
with:
  languages: java
  api_key: ${{ secrets.DATADOG_API_KEY }}
  service: foo
  java-instrumented-build-system: all
```

**Comment by mwisnicki** [comment]
`java-instrumented-build-system` seems to have helped getting test results in fork mode however I've noticed that regardless of this setting and whether forking is enabled, test runs and test suites are disconnected from test session and module. Both for munit and junit. I'm surprised that session didn't propagate even in non-fork mode.

---
Additional minor problem is that I have warning `Warning: dd-java-agent is being initialized more than once` but that's understandable, it's injected by github action and by sbt-datadog plugin. I'll have to figure out how to disable injection from the latter in tests but for now I disabled it completely to eliminate any interference.

Finally there's I think unrelated issue that DataDog sometimes stops updating github comment with reports. I think I saw it before so it's likely not caused by this.

**Comment by mwisnicki** [comment]
It's interesting that even with `Test/fork := false` I see two OpenJDK and dd.trace startup messages as well as
```
Warning: dd-java-agent is being initialized more than once. 
```

**Comment by mwisnicki** [comment]
So an example test run has following tag:
```yaml
test_session:
  fingerprint_v2: 7db8218e3ff2e7d4
  name: test-codegen
```
while disconnected but probably related test session looks like this:
```yaml
test_session:
  fingerprint: 89df8bdf5ab3d8eb
  fingerprint_v2: 7db8218e3ff2e7d4
  name: test-codegen
```

Month ago with `library_version: 1.46.1~8e0205904b` (now 1.47.3) it looked the same but used to work.
