### ISSUE TITLE
Wrong git sha reported from github action test run

### ISSUE THREAD

**Issue by mwisnicki** [DataDog/dd-trace-java#8672]
### Tracer Version(s)

1.47.3

### Java Version(s)

11.0.26

### JVM Vendor

Oracle JDK

### Bug Report

We have a github action workflow triggered by PR that has two jobs:
- test - runs with default commit sha (pr merged with main)
- test-branch - runs with sha of the branch:
```yaml
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
```

It looks like the `git.commit.*` tags might be wrong on `test-branch` job.

We have following git commits involved:
- `06d5eb` - tip of master branch
- `b95c881` - tip of the PR branch (`sbt-10.1`) - used by `test-branch` job
- `84e638` - github generated merge of PR to master (default workflow ref) - used by `test` job

For `test` job a test run in DataDog has following git tags:

<img width="524" alt="Image" src="https://github.com/user-attachments/assets/4c5b0d3f-eeed-4048-a6a9-ff1d1e72035b" />

But for the `test-brach`, corresponding test run has this:

<img width="484" alt="Image" src="https://github.com/user-attachments/assets/54da2afb-7c7e-496d-9423-2599cf23d77a" />

### Expected Behavior

It's showing the same `git.commit.sha` in `test-branch` as `test` job but should be `b95c881` instead, which is the ref that is checked out.
Also `git.commit.message` is missing along with author and commiter.

### Reproduction Code

Both jobs are set up for datadog test optimization:
```yaml
    - name: Configure Datadog Test Optimization
      uses: datadog/test-visibility-github-action@v2
      with:
        languages: java
        api_key: ${{ inputs.datadog-api-key }}
        service: ${{ env.DD_SERVICE }}
```
